server:
  port: 8080

# jpa query log
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: true

spring:
  application:
    name: ddd
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/database/commerce
    username: commerce
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: create-drop